substitutions:
  name: esphome-web-dc73f8
  friendly_name: louder-esp32
  task_stack_in_psram: "false"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.7.2
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: mhetesp32minikit
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

captive_portal:

external_components:
  - source: github://mrtoy-me/esphome-tas58xx@main
    components: [ tas58xx ]
    refresh: 0s
  - source: github://c-MM/esphome-snapclient
    components: [ snapclient ]
    refresh: 0s

network:
  enable_ipv6: true

psram:
  speed: 80MHz

i2c:
  sda: GPIO21
  scl: GPIO27
  frequency: 400kHz
  scan: True

audio_dac:
  - platform: tas58xx
    id: tas5805m_dac
    tas58xx_dac: TAS5805M
    enable_pin: GPIO33
    analog_gain: -5db
    refresh_eq: BY_SWITCH
    dac_mode: BTL
    mixer_mode: STEREO
    volume_max: 0dB
    volume_min: -60db
    update_interval: 4s

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

snapclient:
  hostname: !secret snapserver_ip
  # port: 1704  # default
  name: $friendly_name
  # mute_pin: 18
  audio_dac: tas5805m_dac
  i2s_dout_pin: GPIO22
  # webserver_port: 8080  # start webserver for equalizer

switch:
  - platform: tas58xx
    enable_dac:
      name: Enable Louder
      id: enable_louder
      restore_mode: ALWAYS_ON
    enable_eq:
      name: Enable EQ Control
      restore_mode: ALWAYS_OFF

number:
  - platform: tas58xx
    left_eq_gain_20Hz:
      name: Left Gain ---20Hz
    left_eq_gain_31.5Hz:
      name: Left Gain ---31.5Hz
    left_eq_gain_50Hz:
      name: Left Gain ---50Hz
    left_eq_gain_80Hz:
      name: Left Gain ---80Hz
    left_eq_gain_125Hz:
      name: Left Gain --125Hz
    left_eq_gain_200Hz:
      name: Left Gain --200Hz
    left_eq_gain_315Hz:
      name: Left Gain --315Hz
    left_eq_gain_500Hz:
      name: Left Gain --500Hz
    left_eq_gain_800Hz:
      name: Left Gain --800Hz
    left_eq_gain_1250Hz:
      name: Left Gain -1250Hz
    left_eq_gain_2000Hz:
      name: Left Gain -2000Hz
    left_eq_gain_3150Hz:
      name: Left Gain -3150Hz
    left_eq_gain_5000Hz:
      name: Left Gain -5000Hz
    left_eq_gain_8000Hz:
      name: Left Gain -8000Hz
    left_eq_gain_16000Hz:
      name: Left Gain 16000Hz

sensor:
  - platform: tas58xx
    faults_cleared:
      name: "Times Faults Cleared"
    update_interval: 60s

binary_sensor:
  - platform: tas58xx
    have_fault:
      name: Any Faults
      exclude: CLOCK_FAULT
    left_channel_dc_fault:
      name: Left Channel DC Fault
    right_channel_dc_fault:
      name: Right Channel DC Fault
    left_channel_over_current:
      name: Left Channel Over Current
    right_channel_over_current:
      name: Right Channel Over Current
    otp_crc_check:
      name: CRC Check Fault
    bq_write_failed:
      name: BQ Write Failure
    clock fault:
      name: I2S Clock Fault
    pcdd_over_voltage:
      name: PCDD Over Voltage
    pcdd_under_voltage:
      name: PCDD Under Voltage
    over_temp_shutdown:
      name: Over Temperature Shutdown Fault
    over_temp_warning:
      name: Over Temperature Warning
