# NOTE this YAML config uses the relevant config and external components from
# NOTE the sendspin alpha version which is for testing experimental these new features
# NOTE External componeny references and YAML config will change as software deveopment progresses
# NOTE see https://github.com/esphome/home-assistant-voice-pe-alpha/blob/alpha/home-assistant-voice.yaml

esphome:
  name: louder-s3
  friendly_name: Louder S3
  min_version: 2025.12.0
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 220.0
    then:
      media_player.play_media:
        id: external_media_player
        media_url: file://startup_sync_sound

esp32:
  variant: ESP32S3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      # Optional for ESP32-Louder used by Voice-PE
      # Moves instructions and read only data from flash into PSRAM on boot.
      # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
      # Considerably speeds up mWW at the cost of using more PSRAM.
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

# Enable logging
logger:
  level: DEBUG
  logs:
    number: INFO

api:

ota:
  - platform: esphome
    # password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

http_request:

globals:
  - id: current_volume
    type: float
  - id: announcement_triggered
    type: bool
    initial_value: 'false'

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

external_components:
  - source: github://mrtoy-me/esphome-tas58xx@main
    components: [ tas58xx ]
    refresh: 0s

  - source: github://pr#12253
    components: [mixer]
    refresh: 0s

  - source: github://pr#12254
    components: [resampler]
    refresh: 0s

  - source: github://pr#12256
    components: [audio]
    refresh: 0s

  - source: github://pr#12258
    components: [media_player]
    refresh: 0s

  - source: github://pr#12284
    components: [mdns, sendspin]
    refresh: 0s

  - source: github://pr#12429
    components: [file, http_request, media_source, speaker_source]
    refresh: 0s

i2c:
  sda: GPIO8
  scl: GPIO9
  frequency: 400kHz
  scan: True
  timeout: 100us

audio_dac:
  - platform: tas58xx
    id: tas5805m_dac
    tas58xx_dac: TAS5805M
    enable_pin: GPIO17
    analog_gain: -15.5db
    dac_mode: BTL
    mixer_mode: STEREO
    volume_max: -1dB
    volume_min: -50db
    update_interval: 1s

text_sensor:
  - platform: sendspin
    type: title
    name: Track Title

  - platform: sendspin
    type: artist
    name: Artist

  - platform: sendspin
    type: album
    name: Album

sensor:
  - platform: tas58xx
    faults_cleared:
      name: "Times Faults Cleared"

binary_sensor:
  - platform: tas58xx
    have_fault:
      name: Any Faults # by default clock faults are excluded
    left_channel_dc_fault:
      name: Left Channel DC Fault
    right_channel_dc_fault:
      name: Right Channel DC Fault
    left_channel_over_current:
      name: Left Channel Over Current
    right_channel_over_current:
      name: Right Channel Over Current
    otp_crc_check:
      name: CRC Check Fault
    bq_write_failed:
      name: BQ Write Failure
# I2S clock fault binary sensor is not really useful with speaker media player
# since it generates clock faults when it manipulates I2S.
#   clock fault:
#     name: I2S Clock Fault
    pcdd_over_voltage:
      name: PCDD Over Voltage
    pcdd_under_voltage:
      name: PCDD Under Voltage
    over_temp_shutdown:
      name: Over Temperature Shutdown Fault
    over_temp_warning:
      name: Over Temperature Warning

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14

speaker:
  - platform: i2s_audio
    id: i2s_speaker_id
    sample_rate: 48000
    i2s_dout_pin: GPIO16
    bits_per_sample: 16bit
    dac_type: external
    channel: stereo
    timeout: never
    buffer_duration: 100ms
    audio_dac: tas5805m_dac

  - platform: mixer
    id: mixer_speaker_id
    output_speaker: i2s_speaker_id
    num_channels: 2
    task_stack_in_psram: true
    source_speakers:
      - id: announcement_mixer_input
        timeout: never
      - id: media_mixer_input
        timeout: never

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

sendspin:
  id: sendspin_hub
  task_stack_in_psram: true
  kalman_process_error: 0.01

media_source:
  - platform: sendspin
    id: sendspin_source
  - platform: http_request
    id: http_source
    buffer_size: 500000
  - platform: file
    id: file_source
    files:
      id: startup_sync_sound
      file: https://github.com/mrtoy-me/esphome-tas58xx/raw/main/components/tas58xx/tas58xx_boot.flac

media_player:
  - platform: sendspin
    id: sendspin_group_media_player

  - platform: speaker_source
    id: external_media_player
    name: Media Player
    announcement_speaker: announcement_resampling_speaker
    media_speaker: media_resampling_speaker
    announcement_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 1  # Stereo audio is unnecessary for announcements
      sample_rate: 48000
    media_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 2
      sample_rate: 48000
    volume_increment: 0.05
    sources:
      - file_source
      - http_source
      - sendspin_source
    on_announcement:
      - if:
          condition:
            - lambda: return (!id(announcement_triggered));
          then:
            - lambda: |-
                id(announcement_triggered) = true;
                id(current_volume) = id(external_media_player).volume;
            - mixer_speaker.apply_ducking:
                  id: media_mixer_input
                  decibel_reduction: 40
                  duration: 0.0s
            - wait_until:
                media_player.is_announcing: external_media_player
            - delay: 0.75s
            - media_player.volume_set:
                id: external_media_player
                volume: !lambda "return id(announce_volume).state / 100.0;"
            - wait_until:
                - not:
                    media_player.is_announcing: external_media_player
            - mixer_speaker.apply_ducking:
                      id: media_mixer_input
                      decibel_reduction: 0
                      duration: 1.0s
            - media_player.volume_set:
                id: external_media_player
                volume: !lambda "return id(current_volume);"
            - lambda: id(announcement_triggered) = false;

    on_state:
      if:
        condition:
          and:
            - lambda: return (!id(announcement_triggered));
            - not:
                media_player.is_announcing: external_media_player
        then:
          - mixer_speaker.apply_ducking:
              id: media_mixer_input
              decibel_reduction: 0
              duration: 1.0s


number:
  - platform: template
    name: Announce Volume
    id: announce_volume
    icon: mdi:volume-source
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    restore_value: true
    initial_value: 50
    optimistic: true

  - platform: tas58xx
    left_eq_gain_20Hz:
      name: Left Gain ---20Hz
    left_eq_gain_31.5Hz:
      name: Left Gain ---31.5Hz
    left_eq_gain_50Hz:
      name: Left Gain ---50Hz
    left_eq_gain_80Hz:
      name: Left Gain ---80Hz
    left_eq_gain_125Hz:
      name: Left Gain --125Hz
    left_eq_gain_200Hz:
      name: Left Gain --200Hz
    left_eq_gain_315Hz:
      name: Left Gain --315Hz
    left_eq_gain_500Hz:
      name: Left Gain --500Hz
    left_eq_gain_800Hz:
      name: Left Gain --800Hz
    left_eq_gain_1250Hz:
      name: Left Gain -1250Hz
    left_eq_gain_2000Hz:
      name: Left Gain -2000Hz
    left_eq_gain_3150Hz:
      name: Left Gain -3150Hz
    left_eq_gain_5000Hz:
      name: Left Gain -5000Hz
    left_eq_gain_8000Hz:
      name: Left Gain -8000Hz
    left_eq_gain_16000Hz:
      name: Left Gain 16000Hz

switch:
  - platform: tas58xx
    enable_dac:
      name: Enable Louder
      id: enable_louder
      restore_mode: ALWAYS_ON
    enable_eq:
      name: Enable EQ Control
      restore_mode: RESTORE_DEFAULT_ON
